### ISSUE TITLE
feature: persist log streams for speed

### ISSUE THREAD

**Issue by pmuellr** [smallwins/lambda#2]
I wrote something like `scripts/log.js` last night :-|

I already knew getting these logs would be slow, and it's real f'ing slow.  I'd like to have the ability to persist the data, prolly as it's existing JSON form, locally.  Basically the log command would update all the log streams to disk, then perform it's query over the persisted forms.  You could imagine running some kind of "log updater" in the background, that sync's your logs every few minutes, so the log commands would have even less to do.

Interest?

**Comment by brianleroux** [comment]
yes! I was thinking something like `tail` would be nice for a tmux window or whatevs would be nice

**Comment by pmuellr** [comment]
I ended up finishing my thing, because I needed it badly - https://github.com/pmuellr/lambda-logger

Jury's still out, I think.  Kinda painful to d/l and view as separate steps.  Also figuring out a date range kinda thing for limiting the log output.  Etc, etc.

**Comment by brianleroux** [comment]
super nice---so you keep the cloudwatch logs alive for long periods? (I'm finding we are using them more dev-y and nuking, doing things, looking again, maybe nuke again, etc)

**Comment by pmuellr** [comment]
Ya, why not?  But I haven't seen the bill yet.  I'm sure my story will change :-)

Coupla hours is likely all thats really need for dev, but moving up to staging and production - will need to figure out what a long-term strategy is.

**Comment by brianleroux** [comment]
closing for a future solution that we're baking---stay tuned!
