### ISSUE TITLE
Remove "ok": true for API Gateway?

### ISSUE THREAD

**Issue by kennethormandy** [smallwins/lambda#7]
Hey! This project has been super helpful for me, going from knowing almost nothing about Lambda to getting something online and working, so thanks.

I did encounter a problem getting something to work with API Gateway though, which I admittedly don’t know very much about.

### Works (without `@smallwins/lambda`):

```js
function example (event, context, callback) {
  callback(null, {"statusCode": 200, "body": "results"})
}

exports.handler = example

// Returns "results"
```

Result from API Gateway:

```
Endpoint response body before transformations: {"statusCode":200,"body":"results"}
Endpoint response headers: {x-amzn-Remapped-Content-Length=0, x-amzn-RequestId=0, Connection=keep-alive, Content-Length=35, Date=Tue, 18 Apr 2017 20:13:19 GMT, Content-Type=application/json}
Method response body after transformations: results
Method response headers: {X-Amzn-Trace-Id=Root=0}
Successfully completed execution
Method completed with status: 200
```

### Doesn’t work (with `@smallwins/lambda`):

```js
var lambda = require('@smallwins/lambda')

function example (event, callback) {
  callback(null, {"statusCode": 200, "body": "results"})
}

exports.handler = lambda(example)

// Returns {"message": "Internal server error"}
```

Result from API Gateway:

```
Endpoint response body before transformations: {"statusCode":200,"body":"results","ok":true}
Endpoint response headers: {x-amzn-Remapped-Content-Length=0, x-amzn-RequestId=0, Connection=keep-alive, Content-Length=45, Date=Tue, 18 Apr 2017 20:11:04 GMT, Content-Type=application/json}
Execution failed due to configuration error: Malformed Lambda proxy response
Method completed with status: 502
```

I think [adding `"ok": true`](https://github.com/smallwins/lambda/blob/4b5d5f851cb22a4b01d41cbf263d491d805aba79/_lambda.js#L63) to the object is causing problems. Based on some other issues I read, it didn’t seem like you could deviate from the object that the API Gateway was expecting (`"statsCode"`, `"body"`, and `"headers"` only).

When I modified `@smallwins/lambda` to stop adding "ok": true`, my broken example above worked as expected.

I had some trouble figuring out if that was the only change that needed to be made or if I was just messing up things in the API Gateway, but I tried with both Node v4 and 6 on Lambda and it seemed to resolve the issue.

Happy to open a PR if it makes sense that the change should be made. In the meantime, I’m still using the run scripts, but not this or the validation package.

**Comment by brianleroux** [comment]
so many thoughts---its all dependant on the setup. when api gateway was released we need to have a way to tell it the lambda was erroring or not---you may have seen the weird regexp thing you have to do there. my feels have expanded since but I think it'd be quicker to f2f and I'd love to have a collaborator on them. you free next week for a quick vid chat?

**Comment by kennethormandy** [comment]
Sure, let’s do that. Admittedly since this is my first time using Lambda and API Gateway, I think the only insight I’ll be able to provide is acting as a “user test” with someone who is still trying to understand the pieces. Happy to do that if it’s useful though! Sent you an email about a time for a call.

**Comment by brianleroux** [comment]
closing for now but be in touch soooooon
